# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('shorter', models.SlugField(max_length=4, primary_key=True, serialize=False)),
                ('original', models.URLField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
